import os
import json
import argparse

from langgraph.graph import StateGraph, START, END
from src.utils import GraphState
from agents.plan_executor import build_plan_executor
from agents.plan import plan_agent
from dotenv import load_dotenv

load_dotenv()

def plan_executor_node(state: GraphState):
    """Executes the reasoning plan generated by the planner."""
    input_data = {
        "original_question": state["original_question"],
        "plan": state["plan"],
        "stop": False
    }
    output = plan_executor_agent.invoke(input_data)
    return {"past_exp": [output]}

def parse_args():
    parser = argparse.ArgumentParser(description="Agentic RAG Demo")
    parser.add_argument("--question", type=str, required=True, help="User question to run through the Agentic RAG system")
    parser.add_argument("--exp_name", type=str, default="demo", help="Experiment name for saving outputs")
    parser.add_argument("--model", type=str, default="default-model", help="Model identifier")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()

    # Initialize the agent that executes plans
    global plan_executor_agent
    plan_executor_agent = build_plan_executor()

    # Build the LangGraph workflow (Planner → Executor)
    graph_builder = StateGraph(GraphState)
    graph_builder.add_node("planer_node", plan_agent)
    graph_builder.add_node("plan_executor_node", plan_executor_node)
    graph_builder.add_edge(START, "planer_node")
    graph_builder.add_edge("planer_node", "plan_executor_node")
    graph = graph_builder.compile()

    # Prepare the question
    question = args.question.strip()
    if not question.endswith("?"):
        question += "?"

    inputs = {"original_question": question}

    print("\n🔍 Running Agentic RAG pipeline...\n")
    try:
        output = graph.invoke(inputs)
        print("✅ Final Output:\n")
        print(json.dumps(output, indent=2, ensure_ascii=False))

        # Optionally save to file
        save_dir = f"{args.exp_name}_{args.model}_demo"
        os.makedirs(save_dir, exist_ok=True)
        save_path = os.path.join(save_dir, "demo_output.json")
        with open(save_path, "w") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
        print(f"\n💾 Output saved to: {save_path}\n")

    except Exception as e:
        print("❌ Error during execution:")
        print(e)
